### ISSUE TITLE
Shipping screen doesn't allow for scrolling when keyboard is up

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#101]
When the keyboard is up on the Shipping screen it's really difficult to see what's being entered in text fields as the view doesn't offset itself to compensate for the keyboard. 

It would be good if entry into the field naturally scrolled it into view always. 

See screenshot:

![img_0001](https://cloud.githubusercontent.com/assets/760653/7683428/fe90efa8-fd76-11e4-9863-d94cdfa24a28.PNG)

**Comment by kkarayannis** [comment]
Fixed in ab-testing branch
