### ISSUE TITLE
Photo selection screen selected tick disappears on all selected photos when adding new ones

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#110]
Launch the SDK with remote URL images on the latest Universal branch. Navigate to Prints -> 6" x 4" then add some photos from the camera roll. Notice all blue selected ticks disappear.

**Comment by dbotha** [comment]
In fact just turn the device to landscape on this screen with selected photos will reproduce the issue.

**Comment by kkarayannis** [comment]
Oops, one of the latest commits caused this regression.
