### ISSUE TITLE
Flashing photo in Photo Selection Screen in Landscape

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#118]
Use PC API Key. Select Prints -> Classic 6" x 4". Then add 27 photos from Camera Roll. Turn to landscape. scroll up and down. Notice in the third pack the very first image flashes visible and non visible at certain y scroll offsets.

**Comment by kkarayannis** [comment]
This doesn't seem to be happening anymore. Closing for now, but re-open if you are able to reproduce.
