### ISSUE TITLE
Photobooks: There appears to be no nice shadow decoration under/behind the book

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#144]
See Dans designs -- shadow behind the book is missing

![bug](https://cloud.githubusercontent.com/assets/760653/8006081/4e6a6b7a-0b88-11e5-86bb-b16c3d779e48.png)

**Comment by kkarayannis** [comment]
Ouch, it kinda bad while opening and closing the book.
