### ISSUE TITLE
Photobooks: Weird scrolling glitch

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#159]
1. Progress a few pages in (page 11-12 is a good point)
2. Move so that the right hand page is visible
3. Pan left but very slowly and release your finger so that "auto-panning" to bring the left hand page to the centre takes over. The page should be slowly scrolling into view
4. Now while it's scrolling into view try type put your finger down and scroll again to bring it into view faster. A page turn happens instead which looks really weird as we're still slowly panning.

It would be better if touching down in the "auto-panning" state allowed the user to take control of the scroll again i.e. it's stopped dead and now scroll offset is controlled by dragging my finger.

**Comment by kkarayannis** [comment]
Solved it a bit differently than what you suggested. First, I disabled all interactions during auto panning (wow that will feel unresponsive and horrible I hear you say, but read on). Second the auto panning now has friction, so if you gave it a small initial speed, it will stop mid-way and you can get control of it again. While it will still seem unresponsive during its animation when it's decelerating, hopefully that time will be short, so people won't notice that it's unresponsive.

**Comment by dbotha** [comment]
Haha I'll give it a whirl shortly :)
