### ISSUE TITLE
Photobooks: Open book cover edges are not rounded as per design and righthand cover padding is small

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#161]
Check the open cover corners and make sure they're rounded as per design. Also bottom left corner appears to be missing shadow in transparent pixels. Finally right hand side inner padding is much smaller than top, buttom & left -- all these paddings should be equal.

![bug](https://cloud.githubusercontent.com/assets/760653/8066668/ccd7510c-0ee0-11e5-8a31-3f693ced3d98.png)

**Comment by kkarayannis** [comment]
Great catches!

**Comment by dbotha** [comment]
Ah great work, could you also do front and back cover?

**Comment by kkarayannis** [comment]
Done
