### ISSUE TITLE
Photo selection cell size change from landscape -> portrait bug

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#162]
1. Select a product (photobooks) where photo selection column count is different in portrait vs landscape
2. Add a bunch of photos
3. Proceed to review screen. Move to alternate orientation. 
4. Move back to photo selection view controller -- notice the change in cell size -- ewwww ;)

**Comment by kkarayannis** [comment]
Seems to be fixed in iOS 9.
