### ISSUE TITLE
Photobooks: positioning of page indicator in landscape

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#169]
Could you position it slightly above the bottom of the book itself more inline with the designs -- it's a little more visually appealing

![bug2](https://cloud.githubusercontent.com/assets/760653/8283761/0581dbac-18f1-11e5-9be5-fcc0419a9c9f.png)

**Comment by kkarayannis** [comment]
Positioned it a bit higher and also made it a bit smaller to match the design. However it is still positioned relative to the bottom of the screen and not the book. This way still stay nicely outside of the book when there is a lot of blank space below the book, for example when we have a landscape book.
