### ISSUE TITLE
Photobooks: Jerky scroll on Move Pages screen 

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#176]
If I scroll up and down I occasionally get some very jerky scrolling on my iPhone 6 for a split second. Not sure if this is easily fixable? It happens quite frequently though.

**Comment by kkarayannis** [comment]
You should've seen it in the beginning. At some point, all my commits began with "Performance improvements".
I just did another one, and while I won't say it's perfect, the most noticeable hiccups are gone.

**Comment by dbotha** [comment]
haha ok I'll be the judge of that :P
