### ISSUE TITLE
Photobooks: small pages next to big pages

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#177]
Picture is worth 1000 words :)

I just scrolled up and down a bit until it happened

![img_3728](https://cloud.githubusercontent.com/assets/760653/8522806/3efe9944-23e9-11e5-8576-bd69216b6e08.PNG)

**Comment by dbotha** [comment]
They can end up a range of sizes, not as extreme as the above: 

![img_3729](https://cloud.githubusercontent.com/assets/760653/8522894/f2230fc8-23e9-11e5-9757-c15d0d93a39f.PNG)

**Comment by kkarayannis** [comment]
This one was very tricky to track down but it should be fixed now.
