### ISSUE TITLE
Photobooks: You can double tap "Next" in nav bar on "Move Pages" screen

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#178]
Double or tripple tapping next pushes multiple Review view controllers onto the stack.

**Comment by kkarayannis** [comment]
Fixed for photobooks, although we might have this elsewhere in the SDK as well.

As an aside, how to you feel about changing that button (only on this screen, only for photobooks) from "Next" to "Preview"? My thinking about that is that the user should know that it's "safe" to go forward, that's it's more of a view change than another step. I was even thinking that maybe these 2 screens should be the same, being able to toggle seamlessly between "Edit" and "Review".
