### ISSUE TITLE
Photobooks: Scary console output when testing

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#189]
Particularly the ALAsset one at the top

![screen shot 2015-07-08 at 13 43 29](https://cloud.githubusercontent.com/assets/760653/8570354/9f90fa88-2577-11e5-9012-4f26a9ea9bf5.png)

**Comment by dbotha** [comment]
Hmmmm I still get this?

**Comment by kkarayannis** [comment]
You are not getting the first one though, right? That's the one I was aiming to fix with this issue. I'll take a look at the others too but they don't seem dangerous.

**Comment by kkarayannis** [comment]
OK fixed the rest as well.
