### ISSUE TITLE
Jump to postcard fails with error

### ISSUE THREAD

**Issue by leenyburger** [OceanLabs/iOS-Print-SDK#220]
I'd like to implement a simple postcard implementation.  With the following code : 
```
 OLAsset *frontImage = [OLAsset assetWithImageAsJPEG:[self.itemToEdit photoImage]];
  id<OLPrintJob> postcard = [OLPrintJob postcardWithTemplateId:@"postcard" frontImageOLAsset:frontImage backImageOLAsset:nil];
 OLPrintOrder *order = [[OLPrintOrder alloc] init];
 [order addPrintJob:postcard];
 OLKiteViewController *vc = [[OLKiteViewController alloc]initWithPrintOrder:order];
  [self presentViewController:vc animated:YES completion:nil]; 
```

This fails after the user enters their address/email/phone number with the following error: 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSSetM addObject:]: object cannot be nil'

**Comment by kkarayannis** [comment]
We currently don't have UI in place to view or edit postcards, so you need to pass the final postcard order to the payment view controller:
`OLPaymentViewController *vc = [[OLPaymentViewController alloc] initWithPrintOrder:printOrder];`
