### ISSUE TITLE
"Start Creating" Button in OLProductDetailsViewController does nothing

### ISSUE THREAD

**Issue by scosman** [OceanLabs/iOS-Print-SDK#227]
The "Start Creating" button in the details section does not do anything. 

Pod Version: 4.3.2

**Comment by scosman** [comment]
Small note: the poster control has the same issue.

**Comment by jjxtra** [comment]
I also see this bug. Seems like an easy fix...

**Comment by kkarayannis** [comment]
This screen got a minor design tweak in the release I pushed just a few minutes ago (4.4.0) and this is no longer an issue.
