### ISSUE TITLE
The OLProductHomeViewController has a white bar at the top

### ISSUE THREAD

**Issue by scosman** [OceanLabs/iOS-Print-SDK#228]
See screenshot below. The cause is where you set `self.collectionView.contentInset = UIEdgeInsetsMake(...)` in OLProductHomeViewController. You shouldn't need an inset if the bar is opaque (the default I got after installing). Deleting that line fixed the issue. Not disabling `automaticallyAdjustsScrollViewInsets ` would probably cover both cases without special code.

![screenshot 2015-11-18 12 19 46](https://cloud.githubusercontent.com/assets/848343/11311262/b038405a-8f9c-11e5-8a18-dd973b232166.png)

**Comment by kkarayannis** [comment]
Fixed in 4.3.4
