### ISSUE TITLE
userEmail not prefilled when using

### ISSUE THREAD

**Issue by scosman** [OceanLabs/iOS-Print-SDK#229]
`OLKiteViewController.userEmail` isn't filled out for the user if they use the standard flow ("OLKiteViewController > ProductHomeViewController > etc"). It seems to just be ignored and the user must type their email.

**Comment by vondiplo** [comment]
I'm having this issue as well

**Comment by kkarayannis** [comment]
This issue is fixed in the latest release, version 4.3.3
