### ISSUE TITLE
Cocoapod refuses to build with use_frameworks

### ISSUE THREAD

**Issue by mergesort** [OceanLabs/iOS-Print-SDK#237]
Hi there, love the SDK!

We're trying to move to having our Cocoapods `use_frameworks` to use modules (and speed up compilation time, and interoperate more easily with Swift). Our last remaining issue appears to be that the `Kite_Print_SDK` doesn't seem to be able to build with `use_frameworks` enabled in our podfile.

I've attached a [sample project](https://github.com/OceanLabs/iOS-Print-SDK/files/72018/KiteTest.zip). Any suggestions would be greatly appreciated.

Thanks!

**Comment by mergesort** [comment]
I submitted a PR to fix one issue (https://github.com/OceanLabs/iOS-Print-SDK/pull/238), but that leaves it still with these errors: 

```Include of non-modular header inside framework module 'CSStickyHeaderFlowLayout.CSStickyHeaderFlowLayout'``` 

```Include of non-modular header inside framework module 'Kite_Print_SDK.LXReorderableCollectionViewFlowLayout'```

**Comment by dbotha** [comment]
Thanks @mergesort, we'll take a look when we get back into the office after the Christmas break!

**Comment by mergesort** [comment]
Haha, wouldn't expect this to be fixed over the vacation. Have a great holiday! 🎅🏽

**Comment by kkarayannis** [comment]
This issue was actually fixed last week on the beta branch. I have now patched the same changes on master.

**Comment by mergesort** [comment]
@kkarayannis I just tried integrating 4.5.8. Everything looks great, except it still has this [issue](https://github.com/OceanLabs/iOS-Print-SDK/pull/238), and won't compile when in a module as a result. I changed it locally and everything works great, but it should be done here as well.

**Comment by kkarayannis** [comment]
@mergesort It should be fixed now
