### ISSUE TITLE
crash when trying to select Facebook or Instagram photos

### ISSUE THREAD

**Issue by sebnun** [OceanLabs/iOS-Print-SDK#240]
Hello, I get an exception:

[OLPhotoSelectionViewController assetsPickerController:shouldSelectAsset:]: unrecognized selector sent to instance 0x1...

when I try to select photos from Instagram or Facebook on certain products.
It seems the exception only happens in products that present the "choose Camera Instagram Facebook" options as buttons, not as an UIActionSheet

For example, it works fine when selecting facebook or instagram photos for a case product, but it throws the exception when selecting instagram, facebook photos for a frame or magnet.
Selecting photos from the camera works fine in every scenario.

My app has target iOS 7 and I'm creating the the OLKiteViewController with an empty OLAsset array

Also, I added "define OL_KITE_OFFER_INSTAGRAM;" to OLKitePrintSDK.h
I don't know if this is the correct way to enable instagram, because the instructions on https://github.com/OceanLabs/iOS-Print-SDK/blob/master/Kite-SDK/docs/social_photo_sources.md
were not enough to enable instagram on my app, maybe I'm doing something wrong

**Comment by aliehanani** [comment]
Same here, please find below sample error that's thrown. It occurs regardless of target build, and it been the case with the last few updates. Thanks for all your efforts

2016-01-06 03:15:30.860 *[41978:4921136] -[NXOAuth2PostBodyStream open] Stream has been reopened after close
2016-01-06 03:15:43.497 *[41978:4899423] Adding 0 duplicates
2016-01-06 03:16:21.709 *[41978:4899423] -[OLPhotoSelectionViewController assetsPickerController:shouldSelectAsset:]: unrecognized selector sent to instance 0x7fe19274d720
2016-01-06 03:16:21.901 *[41978:4899423] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OLPhotoSelectionViewController assetsPickerController:shouldSelectAsset:]: unrecognized selector sent to instance 0x7fe19274d720'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001140afe65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000114571deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001140b848d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000114005727 ___forwarding___ + 487
	4   CoreFoundation                      0x00000001140054b8 _CF_forwarding_prep_0 + 120
	5   Printfest                           0x000000010fcced3c -[OLPhotoSelectionViewController instagramImagePicker:shouldSelectImage:] + 108
	6   Printfest                           0x000000010fbcca30 -[OLInstagramImagePickerViewController collectionView:shouldSelectItemAtIndexPath:] + 432
	7   UIKit                               0x00000001129342a9 -[UICollectionView _selectItemAtIndexPath:animated:scrollPosition:notifyDelegate:] + 191
	8   UIKit                               0x0000000112956049 -[UICollectionView touchesEnded:withEvent:] + 574
	9   UIKit                               0x00000001122efef7 forwardTouchMethod + 349
	10  UIKit                               0x00000001122effc0 -[UIResponder touchesEnded:withEvent:] + 49
	11  UIKit                               0x00000001122efef7 forwardTouchMethod + 349
	12  UIKit                               0x00000001122effc0 -[UIResponder touchesEnded:withEvent:] + 49
	13  UIKit                               0x00000001125bcede _UIGestureRecognizerUpdate + 10279
	14  UIKit                               0x0000000112152f8a -[UIWindow _sendGesturesForEvent:] + 1137
	15  UIKit                               0x00000001121541c0 -[UIWindow sendEvent:] + 849
	16  UIKit                               0x0000000112102b66 -[UIApplication sendEvent:] + 263
	17  UIKit                               0x00000001120dcd97 _UIApplicationHandleEventQueue + 6844
	18  CoreFoundation                      0x0000000113fdba31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	19  CoreFoundation                      0x0000000113fd195c __CFRunLoopDoSources0 + 556
	20  CoreFoundation                      0x0000000113fd0e13 __CFRunLoopRun + 867
	21  CoreFoundation                      0x0000000113fd0828 CFRunLoopRunSpecific + 488
	22  GraphicsServices                    0x00000001162c8ad2 GSEventRunModal + 161
	23  UIKit                               0x00000001120e2610 UIApplicationMain + 171
	24  Printfest                           0x000000010fa5380f main + 111
	25  libdyld.dylib                       0x000000011535992d start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dbotha** [comment]
@sebnun @aliehanani Thanks both - will get on this asap!

**Comment by aliehanani** [comment]
I've not had any problems replicating the issue with the Sample app; thus, base on the error, I'd copied the codes from the Sample App's (Kite Print SDK/Controller/Edit-Review/OLPhotoSelectionViewController.m) PhotoSelectionViewController.m and replaced it with that of the built SDK 4.6.0's OLPhotoSelectionViewController.m (via cocoapods), and that worked.

**Comment by kkarayannis** [comment]
This has now been fixed. Sorry for the frustration this has caused.
