### ISSUE TITLE
Reopening OLKiteViewController with assets second time

### ISSUE THREAD

**Issue by crc1559** [OceanLabs/iOS-Print-SDK#244]
If I create a OLKiteViewController after an IBAction and pass it an array of OLAssets, the images load fine. After navigating back to the screen with the IBAction and performing the same IBAction to reopen the OLKiteViewController, some, if not all of the images are missing.

    @IBAction func orderProductsPressed(sender: UIButton) {

        var images = [OLAsset]()
        let url = NSURL(string: "myurlhere")

        SDWebImageManager().downloadImageWithURL(url, options: SDWebImageOptions.RetryFailed, progress: nil, completed: {(image, error, cached, finished, url) in
                if finished {
                    imageAsset = OLAsset(imageAsJPEG: image)
                    images.append(imageAsset)
                }
            })

        let kiteViewController = OLKiteViewController.init(assets: images)
        self.presentViewController(kiteViewController!, animated: true, completion: nil)
    }

**Comment by dbotha** [comment]
@crc1559 did you resolve this satisfactorily?

**Comment by crc1559** [comment]
@dbotha yes sorry for the notification. I do have a question however. If I have loaded assets into the OLKiteViewController, how can I make it so that "Replace Photo" allows me to choose from these assets instead of my camera roll? 

Also, the front cover of a Photo Book is not draggable. It opens my Camera Roll as well. Is this intended?
