### ISSUE TITLE
Error when trying to install Paypal module

### ISSUE THREAD

**Issue by laud** [OceanLabs/iOS-Print-SDK#245]
`> [!] The 'Pods-a' target has transitive dependencies that include static binaries: (/Users/b/Development/c/ios/Pods/PayPal-iOS-SDK/PayPalMobile/libPayPalMobile.a)`

Installing just the base Cocoapod works fine.

**Comment by laud** [comment]
Hmm. I'm guessing this error is caused by my use of `use_frameworks! ` in my Podfile. If there is no way to use `use_frameworks! ` with `pod "Kite-Print-SDK/PayPal"`, I will have to skip using Paypal.

**Comment by rherubin** [comment]
I'm having the same problem

**Comment by UrK** [comment]
It seems that allowing installation of PayPal pod independently and not as a dependency of Kite will allow correct operation of `pod install`. Any chance to remove it from Podspec dependencies and still get PayPal support?
Something like this:
https://github.com/CocoaPods/CocoaPods/issues/2926#issuecomment-136766631

**Comment by kkarayannis** [comment]
The PayPal subspec installation should now work with `use_frameworks!` in the latest version (5.0.4).
Just make sure to add the following in your Podfile:
```pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```

**Comment by laud** [comment]
Cool, thanks!

Just FYI, it appears that `-undefined dynamic_lookup` linker flag that was added conflicts with `ENABLE_BITCODE=YES`..

I get the following, compiler error: `ld: -undefined and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Not enabling bitcode for the KiteSDK target as well as the project target fixes this error.

**Comment by kkarayannis** [comment]
Continuing discussion in issue #247
