### ISSUE TITLE
Problem integrating in swift

### ISSUE THREAD

**Issue by rherubin** [OceanLabs/iOS-Print-SDK#246]
Trying to integrate the ImageProviders (as a cocoapod subspec) in our Swift app and it's not working.

As an example, the subspec doesn't expose the `addCustomPhotoProviderWithCollections` nor the `addCustomPhotoProviderWithViewController` instance methods as stated in the following doc:

https://github.com/OceanLabs/iOS-Print-SDK/blob/master/Kite-SDK/docs/custom_photo_sources.md

**Comment by kkarayannis** [comment]
This is now fixed in the latest version
