### ISSUE TITLE
Using the SDK in a Swift environment

### ISSUE THREAD

**Issue by NickBols** [OceanLabs/iOS-Print-SDK#250]
Hi,

Is this possible as of yet?

After installing with Cocoapods I've tried importing using a header file like so:

#import <OLKitePrintSDK.h>

But I can't seem to call any of the OLKitePrintSDK Methods. Might be missing something easy here.. but haven't really mixed and matched any Obj.C with Swift yet I've been trying to stay away from that :)

**Comment by dbotha** [comment]
Hi @NickBols - totally possible, you need to create a Bridging Header though: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

I'll try make the time today to upload an example Swift project repo

**Comment by NickBols** [comment]
Thanks I look forward to the example! I've read that cocoapods doesn't need a bridging header anymore since update 0.63 and that using 'use_frameworks!' in the podfile should be enough to allow importing/using the pod without issue.. But I'm not seeing it in code completion or anything like that. Would be awesome to have an example with the basic interface!

**Comment by dbotha** [comment]
@NickBols Heres an example Swift project that should launch the SDK if you substitute your test api key in the AppDelegate: https://github.com/OceanLabs/Example-Swift-Kite-Project

Let me know if that works for you?

**Comment by NickBols** [comment]
Yep that works thanks! Not using use_frameworks! in the Podfile and correctly referencing the bridging header file in Build settings -> Code Generation seemed to do it. 2 more questions if you don't mind:

1.When loading a creation page (for example positioning photo on a case) I get a console error saying: "App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. "Temporary exceptions can be configured via your app's Info.plist file. My info.plist looks like this: 
![plistscreen](https://cloud.githubusercontent.com/assets/6424743/14830691/28508e90-0bf2-11e6-8a4b-b6e3b49f3de5.png)
Anything else I should add? Seems to work fine after that though..

2. Is this coming/easily addable: Adding overlaid text on an image in for example the photo book creation page? Would be cool for example to have the user select 20 images (made with the app) and send those together with their 'dateTaken' to the SDK and have it fill the pages with dates overlaid as text for example.

Thanks again for the example project!

**Comment by kkarayannis** [comment]
Hi @NickBols 
- You can find all the entries you need to add to ATS section of the plist [here](https://github.com/OceanLabs/iOS-Print-SDK#ios-9-security)
- Yes, adding text on photo is coming.
- Those scripts come from Cocoapods, not something that KitePrintSDK added or has any control over.

**Comment by NickBols** [comment]
1.Those are the exact ones I added (please view attached screenshot above) and still get that message though.
2. Good to hear looking forward to that update :) 
3. Ok they're disabled for now and it's much quicker, will keep an eye on it.

Thanks!
