### ISSUE TITLE
Amex card formatting

### ISSUE THREAD

**Issue by laud** [OceanLabs/iOS-Print-SDK#251]
A small feature request. Can there be support for American Express card formatting? Specifically, Amex cards use the 15-digit format of `3782 822463 10005`, but it get's displayed as `3782 8224 6310 005`. 

More info about major credit card [formats](https://stripe.com/docs/testing).

![2016-04-25 11 55 05](https://cloud.githubusercontent.com/assets/858939/14795363/0a543ad8-0add-11e6-992e-ad20b19c83ce.png)

**Comment by dbotha** [comment]
@laud This has been added to our backlog, thanks for the heads up!
