### ISSUE TITLE
Cocoapods extremely slow

### ISSUE THREAD

**Issue by scosman** [OceanLabs/iOS-Print-SDK#254]
If I include Kite in my cocoapods project, the "Copy Pod Resources" build step goes from about 1 second to over 30 seconds. The culprit is the ibtool step on the storyboard. Removing it makes it very speedy. This kills our development speed.

Can this be moved to build phase and use the build cache?

**Comment by scosman** [comment]
@kkarayannis any update here? This has been open quite a while.

**Comment by kkarayannis** [comment]
As far as I know, we can't force the storyboard to the build phase. Try integrating Cocoapods with dynamic frameworks by putting `use_frameworks!` at the top of your Podfile. It seems that the framework (including the storyboard) is only compiled once.
Please let me know if that works for you or if it causes any other problems.
