### ISSUE TITLE
Crashing in OLPaymentViewController.validateTemplatePricing

### ISSUE THREAD

**Issue by lenkawell** [OceanLabs/iOS-Print-SDK#259]
Our app is crashing with the latest 5.2.6 version. It's crashing with a bad access in the line that calculates expectedCost. This is because template is nil which causes costDict to be nil. The templateId value in job is "rpi_wrap_210x280_sm", which used to work fine. 

Even if the template name is invalid for some reason, it might be better to validate the template ID somewhere earlier in the code so the app returns an error to the user rather than crashing.

    - (void)validateTemplatePricing{
    NSDecimalNumber *expectedCost = [NSDecimalNumber decimalNumberWithString:@"0"];
    for (id<OLPrintJob> job in self.printOrder.jobs){
        OLProductTemplate *template = [OLProductTemplate templateWithId:[job templateId]];
        
        NSDictionary *costDict = template.originalCostsByCurrencyCode ? template.originalCostsByCurrencyCode : template.costsByCurrencyCode;
        NSDecimalNumber *sheetCost = costDict[[self.printOrder currencyCode]];
        NSUInteger sheetQuanity = template.quantityPerSheet == 0 ? 1 : template.quantityPerSheet;
        NSUInteger numSheets = (NSUInteger) ceil([OLProduct productWithTemplateId:[job templateId]].quantityToFulfillOrder / sheetQuanity);
        NSDecimalNumber *unitCost = [sheetCost decimalNumberByMultiplyingBy:[NSDecimalNumber decimalNumberWithString:[NSString stringWithFormat:@"%lu", (unsigned long)numSheets]]];
        
        float numberOfPhotos = [job assetsForUploading].count;
        if (template.templateUI == kOLTemplateUIPhotobook){
            // Front cover photo should count towards total photos
            if ([(OLPhotobookPrintJob *)job frontCover]){
                numberOfPhotos--;
            }
        }
        
        NSDecimalNumber *numUnitsInJob = [job numberOfItemsInJob];
        
        expectedCost = [expectedCost decimalNumberByAdding:[unitCost decimalNumberByMultiplyingBy:[NSDecimalNumber decimalNumberWithString:[NSString stringWithFormat:@"%ld", (long)([job extraCopies] + 1)*[numUnitsInJob integerValue]]]]];
    }

**Comment by shebbys** [comment]
I just pod updated and its not broken in version 5.3.3
Installing Kite-Print-SDK 5.3.3 (was 5.2.8)
