### ISSUE TITLE
Swift 3 SetApiKey issue

### ISSUE THREAD

**Issue by TeppoHudson** [OceanLabs/iOS-Print-SDK#261]
While using Swift 3 the setting of the APIKey has issues, probably due t o Swift 3 function parameter naming changes:
Swift 2 -> 
OLKitePrintSDK.setAPIKey(<APIKEY>, withEnvironment:kOLKitePrintSDKEnvironmentSandbox)

Swift 3 forces the change to ->
OLKitePrintSDK.setAPIKey(<APIKEY>, with: kOLKitePrintSDKEnvironmentSandbox)

However this get an error when calling the API as "ApiKey not set"

**Comment by kkarayannis** [comment]
I think you just forgot to enter you API key. The automatic code conversion for Swift 3 in Xcode produced this line and it works fine:
```OLKitePrintSDK.setAPIKey("YOUR API KEY", with: kOLKitePrintSDKEnvironmentSandbox)```
