### ISSUE TITLE
Cannot get OLKiteViewController.loadingImageView working

### ISSUE THREAD

**Issue by lenkawell** [OceanLabs/iOS-Print-SDK#262]
I'm trying to use the OLKiteViewController.loadingImageView property to replace the built-in loading image. However it doesn't seem to override the built-in image. Am I doing something wrong? Below is a snip of the Swift code that I'm using.

        if let printOrder = printOrder, let viewcontroller = OLKiteViewController(printOrder: printOrder) {
            viewcontroller.delegate = self.delegate
            viewcontroller.loadingImageView = UIImageView(image: UIImage(named: "PrintShopLoading")) 

}

**Comment by kkarayannis** [comment]
While I haven't tried this in Swift, it should work. Try the following code:
```swift
 if let printOrder = printOrder, let viewcontroller = OLKiteViewController(printOrder: printOrder) {
        viewcontroller.delegate = self.delegate
        let _ = viewcontroller!.view
        viewcontroller.loadingImageView.image = UIImage(named: "PrintShopLoading")
```

**Comment by lenkawell** [comment]
Right, just setting the image in the existing imageView seems to work. Here's what is working for me now:

if let printOrder = printOrder, let viewcontroller = OLKiteViewController(printOrder: printOrder) {
        viewcontroller.delegate = self.delegate
        viewcontroller.loadingImageView?.image = UIImageView(image: UIImage(named: "PrintShopLoading"))
}
