### ISSUE TITLE
How to get analytics data

### ISSUE THREAD

**Issue by lenkawell** [OceanLabs/iOS-Print-SDK#264]
I've just started using the OLKiteDelegate.logKiteAnalyticsEvent to log a user's progress through the shopping, checkout and uploading process. However, in reviewing the code in OLAnalytics.m, I see that it's also logging to a Kite.ly account at MixPanel.

Is there any way for us to see the MixPanel data for our app, possibly somewhere in the Kite.ly dashboard that I haven't discovered yet? Or, can we set up our own MixPanel account and is there an API that I didn't see to set OLAnalytics to use our account instead of the Kite.ly one?

**Comment by kkarayannis** [comment]
Currently there isn't a way to access the existing data or switch MixPanel account. However, you can use OLKiteDelegate.logKiteAnalyticsEvent to log your own analytics events.
