### ISSUE TITLE
Uploading UI could use more status information and help

### ISSUE THREAD

**Issue by lenkawell** [OceanLabs/iOS-Print-SDK#266]
We're discovering that a least a few of our users are not waiting for the upload to complete after they've purchased a book. The upload UI currently only provides a message box that says "Uploading images" and a circle progress indicator. Our assumption is that users don't understand that they should wait for the upload to complete before quitting the app. 

It would be great if there was more explanation about what was happening, approximately how long it will take (time remaining guesstimate), a percentage remaining, maybe a standard progress meter, saying "Uploading book" if the assets are PDFs, etc.

(We're actually not sure how many are having this problem, since we haven't been logging it ourselves and don't have access to the existing analytics data.)

**Comment by kkarayannis** [comment]
The latest version, 6.2, changes the upload message to "Uploading book"
