### ISSUE TITLE
co.oceanlabs.pssdk.OLPrintOrderHistory is >500MB

### ISSUE THREAD

**Issue by lenkawell** [OceanLabs/iOS-Print-SDK#267]
I was looking at one of our test iPads and noticed that the co.oceanlabs.pssdk.OLPrintOrderHistory file is 509MB. Seems like there may be a problem.

**Comment by lenkawell** [comment]
This may be a more critical problem than I first thought since it appears that this entire file is loaded into memory during the checkout process. I've observed that the memory consumption of the app (via Xcode) goes up by roughly the size of the OLPrintOrderHistory file. Likewise, if I delete that file, the memory consumption does not go up.

**Comment by lenkawell** [comment]
The reason that this file is getting so big is because it is archiving each OLPrintOrder, which also archives all of the OLAssets in the order and if any of the assets were created with OLAsset.initWithImageData, then the asset includes all the NSData for the image, which is then archived to the order file. 

The reason that this memory never gets released is because OLPrintOrder+History has a static NSMutableArray *printOrders, which retains a reference to the entire archived file of all the images that were ever printed.

**Comment by kkarayannis** [comment]
Storing the images alongside the order is intentional. Loading them all in memory was not intentional and this has been fixed.
