### ISSUE TITLE
Demo App exception: setObjectForKey: object cannot be nil (key: Product Name)

### ISSUE THREAD

**Issue by vegashacker** [OceanLabs/iOS-Print-SDK#273]
Got app demo app to compile using Cocoapods. Made a new account, got my sandbox key and added it to ViewController.m, and then after running app on Simulator I get above crash in line 378 of OLAnalytics.m. I didn't see any instructions specific to the demo app, so feel free to direct me to those if I've simply missed a step.

**Comment by kkarayannis** [comment]
Thanks for bringing this to our attention. This has now been fixed.
