### ISSUE TITLE
All items OLAssets selected

### ISSUE THREAD

**Issue by BillyJohn3** [OceanLabs/iOS-Print-SDK#277]
I have function in my app to collect up all the URLs of images I wish to display and make an OLAsset assetWithURL for each URL.
But, when I present the view controller and pass it this array of OLAssets when the user  comes to select the images they with to use (say for a print) all the images in the Array I passed are selected. How can I make it default to not having any selected?

Also how can I hide the 'camera role' selecting ability?

**Comment by kkarayannis** [comment]
Hi @BillyJohn3 

You can do that by initializing OLKiteViewController without any assets:
```obj-c
OLKiteViewController *vc = [[OLKiteViewController alloc] initWithAssets:@[]];
```
and add your URL assets in the following way:
```
OLImagePickerProviderCollection *dogsCollection = [[OLImagePickerProviderCollection alloc] initWithArray:@[[OLAsset assetWithURL:[NSURL URLWithString:@"https://s3.amazonaws.com/psps/sdk_static/5.jpg"]], [OLAsset assetWithURL:[NSURL URLWithString:@"https://s3.amazonaws.com/psps/sdk_static/6.jpg"]], [OLAsset assetWithURL:[NSURL URLWithString:@"https://s3.amazonaws.com/psps/sdk_static/7.jpg"]], [OLAsset assetWithURL:[NSURL URLWithString:@"https://s3.amazonaws.com/psps/sdk_static/8.jpg"]]] name:@"Dogs"];

[vc addCustomPhotoProviderWithCollections:@[dogsCollection] name:@"Dogs" icon:[UIImage imageNamed:@"dog"]];
```

You can add a second `OLImagePickerProviderCollection` to organize your images in albums (1st attached screenshot) or you can call `addCustomPhotoProviderWithCollections:name:icon:` a second time to add a second tab (2nd attached screenshot).

Finally, you can hide the camera roll like this:
```
vc.disableCameraRoll = YES;
```

My examples are written in Objective-c but it should work similarly in Swift.

![simulator screen shot 30 mar 2017 4 01 52 pm](https://cloud.githubusercontent.com/assets/181362/24508185/069d5618-1563-11e7-8153-f23c3ea8bd68.png)
![simulator screen shot 30 mar 2017 4 01 10 pm](https://cloud.githubusercontent.com/assets/181362/24508186/078c43ae-1563-11e7-99d8-5e34695da9ec.png)

**Comment by BillyJohn3** [comment]
Positively amazing, thanks.

Is it the case that I can only use OLAssetWithURL for jpeg images? I'm getting an error 'JPEGDecompressSurface : Picture decode failed e00002d1'

Thanks once again, adding onto an app really is as easy is it says.

**Comment by kkarayannis** [comment]
PNGs should also work fine. If this continues to be a problem, please open a new issue and I'll look into it.
