### ISSUE TITLE
Print at Home missing delegate

### ISSUE THREAD

**Issue by gdimoff** [OceanLabs/iOS-Print-SDK#278]
When I'm trying to dismiss the Print at Home viewController it fails and returns this message:

"No MPPrintDelegate or MPAddPrintLaterDelegate has been set to respond to the end of the print flow.  Implement one of these delegates to dismiss the Page Settings view controller."

Meaning you are missing some delegates !

**Comment by kkarayannis** [comment]
You could add the following methods to your OLKiteDelegate object if you have one, as the Print at Home delegate was set to that:
```objective-c
- (void)didCancelPrintFlow:(UIViewController *)printViewController{
    [printViewController dismissViewControllerAnimated:YES completion:NULL];
}
- (void)didFinishPrintFlow:(UIViewController *)printViewController{
    [printViewController dismissViewControllerAnimated:YES completion:NULL];
}
```

However, this was missing from the documentation. As a way of simplifying things, the newest version, v6.5.3, handles the delegate method calls internally if the OLKiteDelegate object doesn't handle them.
