### ISSUE TITLE
Ability to launch OLKiteViewController with promo code

### ISSUE THREAD

**Issue by danielch92** [OceanLabs/iOS-Print-SDK#280]
Hi,

Is it possible to launch OLKiteViewController with default promo code? Or will this be supported in the near future? 

We want to have the ability to apply default promo code to certain class of our users to always give them discount on Kite Print products. We should have the ability to set promo code in the asset or OLKiteViewController just like in the OLPrintOrder. Ideally, once the OLKiteViewController is initialized with default promo code, the SDK should handle the rest like before.   

Thanks!

**Comment by kkarayannis** [comment]
That is indeed possible. Just set:
```obj-c
[OLUserSession currentSession].printOrder.promoCode
```

Let me know if you have any problems with it
