### ISSUE TITLE
Delivery Address / Credit Card details not saved?

### ISSUE THREAD

**Issue by sabiland** [OceanLabs/iOS-Print-SDK#286]
It seems that after relaunching my app sometimes Delivery Address or Credit Card details are not saved?

**Comment by warbeerocks1** [comment]
Have you tried using a billing service such as Google cloud?

**Comment by kkarayannis** [comment]
@sabiland Yes, credit card details are not meant to be saved. Delivery address should be saved just not selected in the basket.
