### ISSUE TITLE
Stripe 8.0.7 vs 11.0.0

### ISSUE THREAD

**Issue by sabiland** [OceanLabs/iOS-Print-SDK#287]
Is it ok to update Stripe to 11.0.0 ?

Kite.ly SDK instructions suggests Stripe 8.0.7.

**Comment by lenkawell** [comment]
Is there any resolution for this question? Stripe 8.0.7 doesn't build well in XCode 9.0 when targeting iOS 10+. Semantic and ARC issues as well as a number of deprecations.

**Comment by kkarayannis** [comment]
I have tested Stripe version 11.3.0 and it is ok. I will update the docs in the next release.

**Comment by lenkawell** [comment]
Thanks! It seems to work well in our testing, though even 11.3.0 still has quite a few deprecated API warnings. Hopefully they'll be fixing it.

**Comment by kkarayannis** [comment]
Update: Turns out 11.3.0 works well in debug mode, but crashes in release mode. Some optimization is causing the crash, but I haven't had the time to find a workaround.
In the meantime, Stripe version 10.1.0 is the latest safe version and I recommend using that.

**Comment by sabiland** [comment]
Thx for info.

**Comment by lenkawell** [comment]
How did you get it to crash? I've tested it compiling with Release mode optimizations with XCode 9.0.1 with an iOS Deployment Target set to 10.0 and I haven't had a crash yet.

**Comment by kkarayannis** [comment]
A new version, v7.0.0, which includes a new checkout experience is now live. The latest Stripe release is now supported.
