### ISSUE TITLE
PayPal iOS SDK deprecated

### ISSUE THREAD

**Issue by dmrschmidt** [OceanLabs/iOS-Print-SDK#293]
Hey there,

on the [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK) page it says

> PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use Braintree Direct

What exactly does this mean when I want to use my own payment flow with your SDK? Will this still work because it is an "existing integration" to your end or is Braintree Direct even compatible out of the box? Or does this not count when I also want my own server to be involved here (e.g. bulk purchases)?
Are bulk purchases supported in general when I run my own server, looks like you require a payment verification with each manual print purchase order.

Thanks,
Dennis

**Comment by kkarayannis** [comment]
Hi! Thanks for bringing the PayPal deprecation notice to our attention. You should be fine using the current PayPal solution. The KiteSDK uses our own PayPal keys so that counts as an existing integration. That said, we will start looking into migrating to Braintree and will update the KiteSDK when that's ready, but I don't expect that to be very soon.

**Comment by dmrschmidt** [comment]
Good to hear. Thanks.

I hope I’m not hijacking github for this question, but with this payment scenario it looks like it is not possible to offer bulk purchases, is that correct? Meaning my app takes a purchase for, say, 5 orders and the users consumes those bit by bit. Since the flow requires a purchase confirmation from the PayPal SDK on your end.

**Comment by kkarayannis** [comment]
Yes you are right that we currently don't have support for bulk purchases like that.
What would you like to accomplish with bulk purchases? Would you like to prepay for some orders on behalf of your users?

**Comment by dmrschmidt** [comment]
Kind of. Two things really (only interested in postcards for now):
* offer "bulk" purchases user can then send over time at a slightly discounted rate
* s.th. like "share the app with x friends and get your first postcard free"

**Comment by kkarayannis** [comment]
The second scenario, you can offer the user a promo code. There's a way to automatically apply a promo code and even hide the promo code field from the user, so it just looks seamless.

The first one sounds like it could be done with promo codes, but it could be tricky. You could take payment yourself up front and offer the user promo codes for future use. Again, you can apply these transparently. These "free" for the user orders will get charged to the credit card that you've entered in the Kite dashboard.

**Comment by dmrschmidt** [comment]
I see. That sounds like that would actually work pretty well for what I have in mind. Thanks a lot for your answers!
