### ISSUE TITLE
App Crash on  OLCustomImagePickerViewControllerDelegate method call

### ISSUE THREAD

**Issue by bharatchandera** [OceanLabs/iOS-Print-SDK#295]
@property (nonatomic, weak) id <OLCustomImagePickerViewControllerDelegate> delegate;

-[OLEditPhotobookViewController assetsPickerController:didFinishPickingAssets:]: unrecognized selector sent to instance 0x7f85eb89a060

SDK ver 6.8.0.

**Comment by kkarayannis** [comment]
Can you provide some steps to reproduce this crash?
Simply adding some photos to a photobook does not cause this crash.

**Comment by kkarayannis** [comment]
This has now been fixed.
