### ISSUE TITLE
7.0.0: Facebook integration version mismatch and forced inclusion

### ISSUE THREAD

**Issue by AlexQuinlivan** [OceanLabs/iOS-Print-SDK#310]
In the previous versions of the SDK, you were able to not include the FBSDKCoreKit and all would be swell. 

Since 7.0.0 the Photobooks pod that the SDK depends on pulls in a version of FBSDKCoreKit, this then enables the default Facebook integration for media selection. (I don't want Facebook)

This also introduces an issue where there's a version mismatch on the Facebook dependency as it depends on `FBSDKCoreKit (~> 4.33.0)` but the print SDK depends on `4.27.1`. 

This version mismatch is also partly why I'm raising this issue, as it seems that if you use `FBSDKCoreKit (~> 4.33.0)` with the print SDK, when tapping the login button for the Facebook provider you'll receive a `EXC_BREAKPOINT`

Is there a way for the sub-pod of Photobooks library to not depend so much on other libraries? Or to at least have the option of removing/replacing those features?

**Comment by kkarayannis** [comment]
We just released a new version of the Photobook pod that removes the requirement for the FB SDK. Running `pod update` should pull the new version.
The other dependencies are necessary at this time.
