### ISSUE TITLE
Photobooks: NavigationBar title and back/close button are not visible

### ISSUE THREAD

**Issue by ricardotokashiki** [OceanLabs/iOS-Print-SDK#317]
When using a white color on navigation bar when we enter on photobook view these items are not visible.

![image](https://user-images.githubusercontent.com/14826660/63432824-37772c80-c422-11e9-8fc4-81f7fb1a7ccb.jpeg)

**Comment by jlandazuri42** [comment]
@ricardotokashiki could you please give us some more detail on your setup?
