### ISSUE TITLE
A new release is required to fix this issue with stripe in Photobooks

### ISSUE THREAD

**Issue by alopix** [OceanLabs/iOS-Print-SDK#320]
https://github.com/OceanLabs/Photobook-iOS/issues/378

**Comment by ricardotokashiki** [comment]
@dbotha @jlandazuri42 Are you planning to release a new version to fix [Stripe](https://github.com/stripe/stripe-ios) issue when working with Xcode 11.4+ ?

**Comment by alopix** [comment]
@ricardotokashiki I was told that this SDK is deprecated and will not be updated at all anymore by Kite.

**Comment by ricardotokashiki** [comment]
@alopix Really? Didn't find anything on their website. 
They don't update anything since 25 Oct 2019 on GitHub.

**Comment by alopix** [comment]
@ricardotokashiki I got the information about it being deprecated via support as there was an issue with the Android SDK as well.
They told me they'd ask their devs to put it on the website, but haven't.

**Comment by ricardotokashiki** [comment]
@alopix They should put it straight away in their website. But thanks for the info!

**Comment by ricardotokashiki** [comment]
@alopix It's here https://www.prodigi.com/mobile-sdk/
Prodigi acquired Kite some time ago

**Comment by alopix** [comment]
@ricardotokashiki Ah yeah, so they updated it on the prodigi website. Not on kite.ly which is where I found all of this 😄
