### ISSUE TITLE
I inserted the name of the city (Ivrea / Italy) and the table is popolutate in this way...

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#35]
![ios simulator screen shot 13 mar 2015 16 39 34](https://cloud.githubusercontent.com/assets/4716015/6641879/f4b36a42-c9a0-11e4-8b48-38596b0bf839.png)

**Comment by dbotha** [comment]
Hi chiarotto, we'll investigate this issue and the other you raised asap. Looks like a simple thing to fix!

**Comment by dbotha** [comment]
Hi @chiarotto -- This issue currently sits with the address lookup service that we use for our address search functionality. Unfortunately it is out of our hands right now until they provide a fix (or not). I'll update you when I know more.

**Comment by chiarotto** [comment]
thx, I hope they will fix it, I really would like to include your print service in my app on the Apple Store.

**Comment by dbotha** [comment]
I'll see if we can't put in our own "fix" for this.
