### ISSUE TITLE
Unclear message if I type Ivrea and If I press "Search"

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#36]
![img_5682](https://cloud.githubusercontent.com/assets/4716015/6642221/4c988d3a-c9a3-11e4-86ae-2df8570f041d.PNG)

**Comment by dbotha** [comment]
Hi @chiarotto , we'll investigate this issue and the other you raised asap. Looks like a simple thing to fix!

**Comment by chiarotto** [comment]
ok thanks!

**Comment by dbotha** [comment]
Hi @chiarotto -- this is now fixed!
