### ISSUE TITLE
Manual insertion of address

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#37]
In the meanwhile I tried to insert the address manually, maybe I found 1 or 3 bugs:

- Line 1
- Line 2
- County

County & Country are redundant.

![img_5713](https://cloud.githubusercontent.com/assets/4716015/6675439/a95a8486-cc20-11e4-90c5-193d3fbf1e6f.PNG)

**Comment by dbotha** [comment]
Hi @chiarotto -- This one isn't actually a bug. County and Country are quite different even if the spelling is close. County is like State / Province. If you provide me the Italian equivalent I can localise that field for you?

**Comment by chiarotto** [comment]
Ok,
Country should be translated in Italian as "Stato" (i.e. Italy, France etc).
County ---> Provincia

**Comment by dbotha** [comment]
Does it make sense to leave the others in English? Happy to provide translations for them all if you let me know what's appropriate. Otherwise I'll go with just these two.

**Comment by chiarotto** [comment]
It is ok like it is. My iphone language is set to english.

What would be nice is to have a preview of the OAsset passet to OLKiteViewController in the following image. In other words the user can already have and idea of its picture on its mac :+1: 

![stickers](https://cloud.githubusercontent.com/assets/4716015/6678044/f1dd0e94-cc35-11e4-8e32-9df0c27f3e8b.png)


Just a nice to have! :-)

Last question about payment with credit card. Do you handle the insertion of "secure code" of the credit card?

**Comment by dbotha** [comment]
I love that as a nice to have! :smile:  At some point I actually want to do something similar across all product photography to give the user a bit of context. We've already got an item on our backlog for this so it will get picked up sometime in the future but many more urgent things getting tackled over the next few weeks first.

**Comment by dbotha** [comment]
What do you mean by insertion of "secure code"? i.e. 3/4 digit CVV on the back of the card? Or 3-D secure -- http://en.wikipedia.org/wiki/3-D_Secure?

**Comment by chiarotto** [comment]
Yes I mean 3-D Secure, usually it requires an additional password to make the order.

**Comment by dbotha** [comment]
Hi @chiarotto , we don't make use of 3D Secure so the user will never be asked to enter parts of their memorable info / password as per of the payment process. They'll be able to make payments just fine without it :)
