### ISSUE TITLE
Available type of payments?

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#38]
In README.md there is a screenshot showing the available payments. There is also "Apple Pay". But runining on my iphone only one type of payment is shown:
![img_5714](https://cloud.githubusercontent.com/assets/4716015/6675586/cfd1eb9e-cc21-11e4-8a61-8a4fb4e97882.PNG)

**Comment by dbotha** [comment]
Hi @chiarotto , ApplePay is unfortunately only available in the USA right now so we won't be able to enable that for you until Apple makes it more widely available. As soon as they do we'll make it available! You can add PayPal though, ensure both of the following are in your Podfile:

pod "Kite-Print-SDK", "~> 2.0"
pod "Kite-Print-SDK/PayPal", "~> 2.0"
