### ISSUE TITLE
Payment with credit card does not function

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#41]
Payment with credit card does not work

![xxx_failed](https://cloud.githubusercontent.com/assets/4716015/6768978/eba9456a-d086-11e4-9c11-a522150598a7.png)

Do you use paypal also for payment with credit card? Later you ask to register to paypal?

**Comment by dbotha** [comment]
Hi @chiarotto ,

Are you using the sandbox or live environment? If you're using the sandbox environment don't use real card details as paypal doesn't like that - rather something fake but that still validates (http://www.getcreditcardnumbers.com):

4485 1748 9131 1457
12/20
123

If you're getting that message with the live environment then it's definitely a bug as that should not be the case.

We use the PayPal REST API to process details entered by this form but we won't later ask the user to log in with PayPal. If they want to pay using their PayPal email address they can select the pay with PayPal button.

Hope that helps :)

**Comment by chiarotto** [comment]
Ok, I'm using test env. May i filter the product? May i show only a subset of products to end user?

**Comment by dbotha** [comment]
Indeed you can, see: https://github.com/OceanLabs/iOS-Print-SDK/blob/master/Kite%20SDK/docs/OLKitePrintSDK.md#sample-code
