### ISSUE TITLE
Enable products

### ISSUE THREAD

**Issue by chiarotto** [OceanLabs/iOS-Print-SDK#42]
If I try to enable this product:

 [OLKitePrintSDK setAPIKey:TestAPIKey withEnvironment:kOLKitePrintSDKEnvironmentSandbox];
 OLProduct *stickers_square = [OLProduct productWithTemplateId:@"stickers_square"];
 [OLKitePrintSDK setEnabledProducts:@[stickers_square]];

But where I try to show you controller:
 OLAsset *asset = [OLAsset assetWithImageAsJPEG:[UIImage imageWithData:data]];
 OLKiteViewController *vc = [[OLKiteViewController alloc] initWithAssets:@[asset]];
 [self presentViewController:vc animated:YES completion:NULL];

I get the below error. If I remove the line
[OLKitePrintSDK setEnabledProducts:@[stickers_square]];

then non exceptions are thrown. 

2015-03-22 21:55:42.835 sbapix[4533:74485] -[OLProductOverviewViewController setUserEmail:]: unrecognized selector sent to instance 0x7fa4e3cb24b0
2015-03-22 21:55:42.838 sbapix[4533:74485] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OLProductOverviewViewController setUserEmail:]: unrecognized selector sent to instance 0x7fa4e3cb24b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f643a75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ef30bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010f64ad1d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010f5a29dc ___forwarding___ + 988
	4   CoreFoundation                      0x000000010f5a2578 _CF_forwarding_prep_0 + 120
	5   sbapix                              0x000000010b44cfe4 -[OLKiteViewController transitionToNextScreen:] + 1476
	6   sbapix                              0x000000010b44bc9f -[OLKiteViewController viewDidLoad] + 287
	7   UIKit                               0x000000010cf13580 -[UIViewController loadViewIfRequired] + 738
	8   UIKit                               0x000000010cf1377e -[UIViewController view] + 27
	9   UIKit                               0x000000010d4b6f4e -[_UIFullscreenPresentationController _setPresentedViewController:] + 65
	10  UIKit                               0x000000010ceeed69 -[UIPresentationController initWithPresentedViewController:presentingViewController:] + 105
	11  UIKit                               0x000000010cf1f531 -[UIViewController _presentViewController:withAnimationController:completion:] + 1746
	12  UIKit                               0x000000010cf21871 __62-[UIViewController presentViewController:animated:completion:]_block_invoke + 132
	13  UIKit                               0x000000010cf21795 -[UIViewController presentViewController:animated:completion:] + 229
	14  sbapix                              0x000000010b332605 __47-[CompositionsViewController printSelectedCell]_block_invoke + 517

**Comment by dbotha** [comment]
Hi @chiarotto , sorry for the delay in getting back to you. We were heads down getting out the next version of the SDK that includes Facebook & Instagram image picking support on top of just the camera roll. I'll take a look into the above today!

**Comment by dbotha** [comment]
Hi @chiarotto , After much discussion with the team we've decided to remove client side selection of active products entirely. This will now be done in the Kite dashboard. You'll be able to toggle products on and off that will dynamically update in the SDK in realtime. I suspect this functionality will come along at some point next week with an SDK and dashboard update. Sorry for the trouble you've had.

**Comment by dbotha** [comment]
Hi @chiarotto , Just a quick update - We'll be starting work on this functionality today in the web dashboard. I'll drop you a another update when it's available.

**Comment by chiarotto** [comment]
ok thx

**Comment by dbotha** [comment]
@chiarotto This has now been resolved as the Kite dashboard now allows you to dynamically toggle products available in the SDK. Log in and the select "Products" on the left hand menu and finally select "Add / Remove Products" button on the top right.

In the latest version of the SDK (2.0.20) you can also enable filter clientside product filtering using:

    OLKiteViewController *vc = [[OLKiteViewController alloc] initWithAssets:assetsForPrinting];
    vc.filterProducts = @[@"magnets"];

Hope that helps :)
