### ISSUE TITLE
Print shop product category/group screen needs placeholder tile in landscape

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#83]
When there are an uneven number of categories/groups and the home view controller is used in landscape there is a blank tile which should preferably be a placeholder tile.

**Comment by kkarayannis** [comment]
That's weird. That's already there, and I saw it load on a fresh install. Maybe you have something cached on your device?

**Comment by kkarayannis** [comment]
I was looking at something else. Fixed.
