### ISSUE TITLE
Landscape support for Facebook & Instagram image pickers

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/iOS-Print-SDK#95]
Sorry again I know these are due to myself :(

Launching the Instagram or Facebook image picker when in landscape and then returning to the photo selection view controller screen leaves it looking like this:

![img_0012](https://cloud.githubusercontent.com/assets/760653/7374585/1956c1f2-edcb-11e4-94b4-b0cddc290497.PNG)

**Comment by kkarayannis** [comment]
Instagram: https://github.com/OceanLabs/InstagramImagePicker-iOS/pull/2/files
Facebook: https://github.com/OceanLabs/FacebookImagePicker-iOS/pull/4
